### PR TITLE
moment.js upgrade

### PR DESCRIPTION
**Pull request by ddzhagayev**
sugessting to update moment.js up to 2.10.6 #52

### CODE REVIEW

**Comment by PavelPolyakov** [comment]
@mobinni 
Please, update the bower package, because this takes no effect now

**Comment by mobinni** [comment]
Not to be rude, you know you could always fork your own version and fix it there :smile: 
I'm sorry it took so long to merge this, I've been extremely busy.

**Comment by mobinni** [comment]
Published

**Comment by PavelPolyakov** [comment]
@mobinni 
Thanks. Sure thing I was not offending you :) Just wanted to point this out, in case it was forgotten.

Regards,

**Pull request merged**
